export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const ADD_SHIPPING_ADDRESS_TO_CART = 'ADD_SHIPPING_ADDRESS_TO_CART'
export const ADD_PAYMENT_METHOD_TO_CART = 'ADD_PAYMENT_METHOD_TO_CART'