export const PRODUCTLIST_REQUEST = 'PRODUCTLIST_REQUEST'
export const PRODUCTLIST_SUCCESS = 'PRODUCTLIST_SUCCESS '
export const PRODUCTLIST_ERROR = 'PRODUCTLIST_ERROR'
export const PRODUCTDETAILS_REQUEST = 'PRODUCTDETAILS_REQUEST';
export const PRODUCTDETAILS_SUCCESS = 'PRODUCTDETAILS_SUCCESS';
export const PRODUCTDETAILS_ERROR = 'PRODUCTDETAILS_ERROR';



export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS '
export const PRODUCT_DELETE_ERROR =   'PRODUCT_DELETE_ERROR'


